### ISSUE TITLE
'npm install' execution has been blocked

### ISSUE THREAD

**Issue by xuruijing** [mistakia/record-node#1]
To download this project, execute the command NPM install, which is blocked at the following location. Is there anything missing?

> leveldown@3.0.0 install /Users/xuruijing/Downloads/record-node-master/node_modules/orbit-db-cache/node_modules/leveldown
> prebuild-install || node-gyp rebuild

**Comment by mistakia** [comment]
Could you share the full npm error log?

**Comment by xuruijing** [comment]
error /Users/xuruijing/Downloads/record-app-master-2/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/xuruijing/Downloads/record-app-master-2/node_modules/electron
Output:
Downloading electron-v2.0.2-darwin-x64.zip
Error: connect ETIMEDOUT 54.231.81.8:443
/Users/xuruijing/Downloads/record-app-master-2/node_modules/electron/install.js:47
  throw err
  ^

Error: connect ETIMEDOUT 54.231.81.8:443
    at Object._errnoException (util.js:1022:11)

**Comment by mistakia** [comment]
It seems like your error has to do with mistakia/record-app as electron is not a dependency of record-node. I'm going to close this issue in favor of mistakia/record-app#2
